# EXERCISE 1

In [1]:
import numpy as np
print("Version of NUMPY :",np.__version__)

Version of NUMPY : 1.16.2


In [2]:
print("Build configuration of NUMPY:",np.show_config())

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New folder\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/New folder\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/New folder\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/New folder\\Library\\include']
bla

# EXERCISE 2

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [4]:
print(np.info(np.shape))

 shape(a)

Return the shape of an array.

Parameters
----------
a : array_like
    Input array.

Returns
-------
shape : tuple of ints
    The elements of the shape tuple give the lengths of the
    corresponding array dimensions.

See Also
--------
alen
ndarray.shape : Equivalent array method.

Examples
--------
>>> np.shape(np.eye(3))
(3, 3)
>>> np.shape([[1, 2]])
(1, 2)
>>> np.shape([0])
(1,)
>>> np.shape(0)
()

>>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
>>> np.shape(a)
(2,)
>>> a.shape
(2,)
None


# Exercise 3

In [5]:
arr=np.arange(12)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
np.isin(0,arr)

array(True)

In [8]:
arr2=np.arange(1,11)

In [9]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.isin(0,arr2)

array(False)

# Exercise 4

In [11]:
print(np.any(arr))

True


In [12]:
arr1=np.array([0,0,0,0])

In [13]:
print(np.any(arr1))

False


# Exercise 5

In [14]:
arr3=np.array([2,3,4,np.nan,np.inf])

In [15]:
print("orginal array",arr3)

orginal array [ 2.  3.  4. nan inf]


In [16]:
print(np.isfinite(arr3))

[ True  True  True False False]


# Exercise 6

In [17]:
arr4=np.array([1,-2,3,np.inf,6,-3])

In [18]:
arr4

array([ 1., -2.,  3., inf,  6., -3.])

In [19]:
print(np.isinf(arr4))

[False False False  True False False]


# Exercise 7

In [20]:
arr5=np.array([2,4,2,np.nan,9])

In [21]:
print(np.isnan(arr5))

[False False False  True False]


# Exercise 8

In [22]:
arr6=np.array([3,2,3,2+3j])

In [23]:
arr6

array([3.+0.j, 2.+0.j, 3.+0.j, 2.+3.j])

In [24]:
print(np.iscomplex(arr6))

[False False False  True]


In [25]:
print(np.isreal(arr6))

[ True  True  True False]


In [26]:
print(np.isscalar([3]))

False


In [27]:
print(np.isscalar(7))

True


# Exercise 9

In [28]:
arr=np.array([2,3,4])

In [29]:
arr1=np.array([3,3,33])

In [30]:
np.greater(arr,arr1)

array([False, False, False])

In [31]:
np.less(arr,arr1)

array([ True, False,  True])

In [32]:
np.greater_equal(arr,arr1)

array([False,  True, False])

In [33]:
arr1[np.less_equal(arr,arr1)]

array([ 3,  3, 33])

# Exercise 10

In [34]:
arr1=np.array([22,33,444,55,333,100])

In [35]:
arr=np.array([22,33,444,55,333,100.00001])

In [36]:
np.greater(arr1,arr)

array([False, False, False, False, False, False])

In [37]:
np.greater_equal(arr1,arr)

array([ True,  True,  True,  True,  True, False])

In [38]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])


In [39]:
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])


In [40]:
x

array([  72,   79,   85,   90,  150, -135,  120,  -10,   60,  100])

In [41]:
y

array([  72.      ,   79.      ,   85.      ,   90.      ,  150.      ,
       -135.      ,  120.      ,  -10.      ,   60.      ,  100.000001])

In [42]:
np.greater(x,y)

array([False, False, False, False, False, False, False, False, False,
       False])

In [43]:
np.greater_equal(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

# Exercise 10

In [44]:
arr=np.array([1,7,13,105],dtype=np.int8)
arr

array([  1,   7,  13, 105], dtype=int8)

# Exercise 11

In [45]:
arr=np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
arr1=np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
arr3=np.ones(10)*5

In [48]:
arr3.astype("int")

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Exercise 12

In [49]:
arr4=np.arange(30,71)


# Exercise 13

In [50]:
arr4[arr4%2==0]

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# Exercise 14

In [51]:
arr=np.arange(30,71,2)

In [52]:
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

# Exercise 15

In [53]:
arr=np.eye(3,3)

In [54]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Exercise 16

In [55]:
arr=np.random.normal()

In [56]:
arr

0.21184716386993843

In [57]:
np.random.normal(size=4)


array([ 0.05222846, -0.08315682,  0.57662823, -0.90642332])

# Exercise 17

In [58]:
arr=np.random.normal(0,1,15)


In [59]:
arr

array([ 0.98239259, -1.64253676,  0.1676246 , -0.29684705, -1.30974067,
        1.22251872,  0.42080329,  0.59145673,  1.01388467, -0.94023486,
       -1.00949371,  3.03972655,  2.00824653, -1.06384534,  1.45025844])

# Exercise 18

In [60]:
arr=np.arange(15,56)

In [61]:
len(arr)

41

In [62]:
arr[1:40]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

# Exercise 19

In [63]:
arr=np.arange(12)

In [64]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
for x in np.nditer(arr):
    print(x,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

# Exercise 20

In [66]:
arr=np.linspace(5,50,10)

In [67]:
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

# CHAPTER NO 4 
## Numpy 

In [68]:
arr=np.ones((2,3))

In [69]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
arr=np.ones_like(arr)

In [71]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
arr=np.arange(12).reshape(3,4)

In [73]:
arr=np.ones_like(arr)

In [74]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [75]:
arr=np.zeros_like(arr)

In [76]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
arr=np.empty_like(arr)

In [78]:
arr

array([[         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248]])

In [79]:
arr=np.full_like(arr,3)

In [80]:
arr

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [82]:
arr=np.arange(10)

In [83]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr=arr.astype('float')

In [87]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
arr1=np.array(['2','3'])

In [89]:
arr1.astype(arr.dtype)

array([2., 3.])

In [90]:
arr1

array(['2', '3'], dtype='<U1')

In [91]:
arr1.dtype

dtype('<U1')

In [92]:
arr1.shape

(2,)

In [93]:
# Arthematic Operation

In [94]:
arr2=np.arange(12).reshape(3,4)

In [95]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr2+arr2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [97]:
arr2-arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [98]:
arr2*arr2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [101]:
arr2//arr2

D:\New folder\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [102]:
arr2**arr2

array([[         1,          1,          4,         27],
       [       256,       3125,      46656,     823543],
       [  16777216,  387420489, 1410065408, 1843829075]], dtype=int32)

In [108]:
arr3=np.array([[2,4,3,2],[3,5,6,7],[6,5,7,9],[6,8,9,0]])

In [107]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
arr2.dot(arr3)

array([[ 33,  39,  47,  25],
       [101, 127, 147,  97],
       [169, 215, 247, 169]])

In [111]:
#indexing and Slicing

In [2]:
import numpy as np

In [2]:
arr=np.arange(20)

In [5]:
arr=arr.reshape(4,5)

In [6]:
arr[1]

array([5, 6, 7, 8, 9])

In [7]:
arr[1,2]

7

In [8]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
arr[0:3,2:3]

array([[ 2],
       [ 7],
       [12]])

In [16]:
arr[3]=4

In [17]:
arr

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [ 4,  4,  4,  4,  4]])

In [20]:
a=arr[:,4]

In [21]:
a.shape

(4,)

# Boolean Indexing

In [25]:
names=np.array(['boo','joe','will','boo','joe','will'])

In [29]:
arr1=np.random.randn(6,4)

In [30]:
names=='boo'

array([ True, False, False,  True, False, False])

In [31]:
arr1[names=='boo']

array([[ 1.15676906, -0.1900201 ,  0.51779492,  0.74978393],
       [-0.55525754,  0.15335657, -2.31244316,  2.44794001]])

In [32]:
arr1

array([[ 1.15676906, -0.1900201 ,  0.51779492,  0.74978393],
       [-0.66055973, -1.28542382, -0.86512281,  0.16933191],
       [ 0.99302453, -1.25443592, -0.00330867,  0.12948144],
       [-0.55525754,  0.15335657, -2.31244316,  2.44794001],
       [-1.78365312, -1.45585037,  0.21926965,  1.60573029],
       [-0.13094725, -0.55723941,  1.51195014, -0.8505103 ]])

In [37]:
arr1[names!='boo',2:]=22
arr1

array([[ 1.15676906, -0.1900201 ,  0.51779492,  0.74978393],
       [-0.66055973, -1.28542382, 22.        , 22.        ],
       [ 0.99302453, -1.25443592, 22.        , 22.        ],
       [-0.55525754,  0.15335657, -2.31244316,  2.44794001],
       [-1.78365312, -1.45585037, 22.        , 22.        ],
       [-0.13094725, -0.55723941, 22.        , 22.        ]])

# Fancy Indexing 

In [39]:
arr=np.arange(12).reshape(3,4)

In [42]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
arr[[2,1,0]][:,[1,0,2]]=2

In [51]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
arr[[1,2,0],[0,1,2]]

array([4, 9, 2])

# Transposing array and Swapping Axes

In [58]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
arr1=np.arange(16).reshape(2,4,2)

In [62]:
arr1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [68]:
arr1.swapaxes(1,0)

array([[[ 0,  1],
        [ 8,  9]],

       [[ 2,  3],
        [10, 11]],

       [[ 4,  5],
        [12, 13]],

       [[ 6,  7],
        [14, 15]]])

In [71]:
# swap doesn't make copy

In [70]:
# fancy indexing make copy

In [74]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
arr=np.arange(24).reshape(2,4,3)

In [77]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [80]:
arr.transpose(2,0,1)

array([[[ 0,  3,  6,  9],
        [12, 15, 18, 21]],

       [[ 1,  4,  7, 10],
        [13, 16, 19, 22]],

       [[ 2,  5,  8, 11],
        [14, 17, 20, 23]]])

# UNIVERSAL FUNCTION

In [3]:
arr=np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
arr1=np.arange(3,23,2)

In [20]:
arr1

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [21]:
len(arr1)

10

In [22]:
np.maximum(arr,arr1)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [23]:
np.minimum(arr,arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.max(arr1)

21

In [26]:
np.max(arr)

9

In [27]:
rem,whole_part=np.modf(arr)

In [28]:
rem

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
whole_part

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
np.floor(arr1)

array([ 3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.])

In [31]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

# binary operations

In [32]:
np.add(arr,arr1)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [33]:
np.subtract(arr,arr1)

array([ -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12])

In [34]:
np.divide(arr,arr1)

array([0.        , 0.2       , 0.28571429, 0.33333333, 0.36363636,
       0.38461538, 0.4       , 0.41176471, 0.42105263, 0.42857143])

In [35]:
np.floor_divide(arr,arr1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [36]:
np.mod(arr,arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [38]:
np.power(arr,arr1)

array([          0,           1,         128,       19683,     4194304,
        1220703125,  2033549312, -2094633337,           0,  1914644777],
      dtype=int32)

In [40]:
np.greater(arr1,arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [41]:
np.greater_equal(arr1,arr)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [42]:
np.where(arr==3,4,arr)

array([0, 1, 2, 4, 4, 5, 6, 7, 8, 9])

In [43]:
arr.mean()

4.5

In [44]:
arr.sum()

45

In [2]:
import numpy as np

In [3]:
arr=np.arange(24).reshape(4,6)

In [4]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
arr.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

In [6]:
arr.mean(axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [8]:
arr.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56]], dtype=int32)

In [10]:
arr.cumprod(axis=1)

array([[       0,        0,        0,        0,        0,        0],
       [       6,       42,      336,     3024,    30240,   332640],
       [      12,      156,     2184,    32760,   524160,  8910720],
       [      18,      342,     6840,   143640,  3160080, 72681840]],
      dtype=int32)

# Sorting

In [16]:
arr=np.arange(10,1,-1)

In [17]:
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [21]:
arr=np.random.randn(6)

In [22]:
arr

array([-0.68524532, -0.54549809,  0.05902439,  0.91291864,  0.67925633,
       -0.241224  ])

In [23]:
arr.sort()

In [24]:
arr

array([-0.68524532, -0.54549809, -0.241224  ,  0.05902439,  0.67925633,
        0.91291864])

In [25]:
arr=np.random.randn(4,3)

In [26]:
arr

array([[-1.40807752,  1.14458442,  0.4048849 ],
       [ 0.95496508,  1.29427471,  0.26873084],
       [-0.67039404,  2.69982396, -0.95055713],
       [-0.05240499, -0.36067717,  0.42525618]])

In [27]:
arr.sort()

In [28]:
arr

array([[-1.40807752,  0.4048849 ,  1.14458442],
       [ 0.26873084,  0.95496508,  1.29427471],
       [-0.95055713, -0.67039404,  2.69982396],
       [-0.36067717, -0.05240499,  0.42525618]])

In [29]:
arr=np.array([2,1,2,4,5,6,6,6,3,2])

In [31]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [34]:
sorted(set(arr))

[1, 2, 3, 4, 5, 6]

In [35]:
x=np.array([1,4,3,5,3,2,1])
y=np.array([1,2,4,5,3,7,55])

In [37]:
np.union1d(x,y)

array([ 1,  2,  3,  4,  5,  7, 55])

In [38]:
np.intersect1d(x,y)

array([1, 2, 3, 4, 5])

In [39]:
arr

array([2, 1, 2, 4, 5, 6, 6, 6, 3, 2])

In [40]:
np.setdiff1d(x,y)

array([], dtype=int32)

In [41]:
np.in1d(x, y)

array([ True,  True,  True,  True,  True,  True,  True])

In [42]:
np.unique(x)

array([1, 2, 3, 4, 5])

# File input and output 

In [43]:
arr

array([2, 1, 2, 4, 5, 6, 6, 6, 3, 2])

In [44]:
np.save('save_array',arr)

In [45]:
np.load('save_array.npy')

array([2, 1, 2, 4, 5, 6, 6, 6, 3, 2])

In [58]:
np.savez('safe',a=x,b=y)

In [59]:
arr=np.load('safe.npz')

In [60]:
arr['b']

array([ 1,  2,  4,  5,  3,  7, 55])

In [61]:
arr

In [62]:
x

array([1, 4, 3, 5, 3, 2, 1])

In [66]:
import random
random.shuffle(x)

In [67]:
x

array([5, 2, 3, 4, 1, 1, 3])

In [69]:
np.sort(x)

array([1, 1, 2, 3, 3, 4, 5])

In [70]:
x

array([5, 2, 3, 4, 1, 1, 3])

In [10]:
import numpy as np

In [11]:
arr=np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr=arr.reshape(5,2)

In [16]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [17]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
arr.ravel('F')

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [22]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
arr=np.arange(12).reshape(3,4)

In [24]:
arr1=np.random.randn(3,4)

In [25]:
np.concatenate([arr,arr1],axis=0)

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 1.24221706,  0.1715073 ,  0.32914618,  0.45446329],
       [-0.32401302, -1.72579597,  0.67671322,  0.26383247],
       [-0.94059817,  1.0695404 , -0.48666016,  0.89844444]])

In [26]:
np.concatenate([arr,arr1],axis=1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  1.24221706,
         0.1715073 ,  0.32914618,  0.45446329],
       [ 4.        ,  5.        ,  6.        ,  7.        , -0.32401302,
        -1.72579597,  0.67671322,  0.26383247],
       [ 8.        ,  9.        , 10.        , 11.        , -0.94059817,
         1.0695404 , -0.48666016,  0.89844444]])

In [27]:
np.hstack((arr,arr1))

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  1.24221706,
         0.1715073 ,  0.32914618,  0.45446329],
       [ 4.        ,  5.        ,  6.        ,  7.        , -0.32401302,
        -1.72579597,  0.67671322,  0.26383247],
       [ 8.        ,  9.        , 10.        , 11.        , -0.94059817,
         1.0695404 , -0.48666016,  0.89844444]])

In [28]:
np.vstack((arr,arr1))

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 1.24221706,  0.1715073 ,  0.32914618,  0.45446329],
       [-0.32401302, -1.72579597,  0.67671322,  0.26383247],
       [-0.94059817,  1.0695404 , -0.48666016,  0.89844444]])

In [29]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
first,sec,third=np.split(arr,[1,2])

In [33]:
first

array([[0, 1, 2, 3]])

In [35]:
sec

array([[4, 5, 6, 7]])

In [36]:
first.repeat(2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [37]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
arr.repeat([2,3,4,1],axis=1)

array([[ 0,  0,  1,  1,  1,  2,  2,  2,  2,  3],
       [ 4,  4,  5,  5,  5,  6,  6,  6,  6,  7],
       [ 8,  8,  9,  9,  9, 10, 10, 10, 10, 11]])

In [42]:
np.tile(arr,2)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [44]:
np.tile(arr,(2,3))

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11]])

In [3]:
arr=np.arange(10)*100

In [4]:
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [5]:
ind=[2,1,6]

In [6]:
arr.take(ind)

array([200, 100, 600])

In [7]:
arr.put(ind,66)

In [8]:
arr

array([  0,  66,  66, 300, 400, 500,  66, 700, 800, 900])

In [9]:
arr=np.arange(12).reshape(3,4)

In [10]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
arr.mean(0)

array([4., 5., 6., 7.])

In [12]:
arr.mean(1)

array([1.5, 5.5, 9.5])

In [13]:
demeaned = arr - arr.mean(0)
demeaned

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])