# practice of numpy


In [1]:
#Q:1

In [2]:
import numpy as np
print("the version of the numpy is:",np.__version__)

the version of the numpy is: 1.16.2


In [3]:
#Q:2

In [4]:
D1=np.arange(0,10)
D1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Q:3

In [6]:
BOOL=np.full((3,3),True)

In [7]:
BOOL

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
BOOL.dtype

dtype('bool')

In [9]:
#ALTERNATIVE METHOD

In [10]:
booll=np.ones((3,3),dtype="bool")

In [11]:
booll

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
#Q:4

In [13]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
a=arr[arr%2==1]
a

array([1, 3, 5, 7, 9])

In [14]:
# Q:5

In [15]:
arr[arr%2==1]=-1

In [16]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
#Q:6 
a1=np.array([0,1,2,3,4,5,6,7,8,9])
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr2=np.where(a1%2==1,-1,a1)
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Q:7

In [21]:
reshap=a1.reshape(2,5)

In [22]:
reshap

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
#Q:8

In [24]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)

b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
#method 1
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
#method 2
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
# method 3
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
# Q:9
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [30]:
# Q:10
a1=np.array([1,2,3])
a2=np.r_[np.repeat(a1,3),np.tile(a1,3)]

In [31]:
a2

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [32]:
# Q:11
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [33]:
np.intersect1d(a,b)

array([2, 4])

In [34]:
#Q:12
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
np.setdiff1d(b,a)

array([6, 7, 8, 9])

In [35]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10.2,7,4,9,4,9,8])

In [36]:
# Q 13
a=np.array([1,2,3,4,5,6,7])
b=np.array([2,2,3,5,4,6,8])
np.where(a==b)

(array([1, 2, 5], dtype=int64),)

In [37]:
# in this question we use where method to find the index position where the condition becomes true

In [38]:
#Q 14
a= np.array([2, 6, 1, 9, 10, 3, 27])
b=np.where((a>5)&(a<10))
a[b]

array([6, 9])

In [39]:
#Q 15
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.maximum(a,b)

array([ 6,  6,  4,  9, 10,  7, 27])

In [40]:
#Q 15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5., 7, 9, 8, 6, 4, 5])
b = np.array([6., 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx)
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [41]:
# vectorize fuction in used to perform pyfucn
#here first parameter is callable function and then otype in which we provide data type of the resultant array

In [42]:
# Q 16

In [43]:
a=np.arange(9).reshape(3,3)

In [44]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [46]:
# Q 17
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [48]:
# Q 18
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [50]:
arr=np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [52]:
# Q 20
arr=np.random.uniform(5,10,size=(5,3))

In [53]:
arr

array([[5.23633676, 9.36859333, 7.03161078],
       [5.45251431, 9.72510407, 9.60883656],
       [5.97187316, 7.17836673, 5.82725368],
       [5.22738052, 7.51413645, 7.67997924],
       [8.82856503, 7.71887468, 5.84982508]])

In [54]:
# Q 21
arr

array([[5.23633676, 9.36859333, 7.03161078],
       [5.45251431, 9.72510407, 9.60883656],
       [5.97187316, 7.17836673, 5.82725368],
       [5.22738052, 7.51413645, 7.67997924],
       [8.82856503, 7.71887468, 5.84982508]])

In [55]:
arr=np.random.random((5,3))

In [56]:
arr

array([[0.68897895, 0.35626549, 0.47954866],
       [0.31542193, 0.4872746 , 0.00379747],
       [0.01210403, 0.79976761, 0.49282379],
       [0.08271371, 0.68871899, 0.54570463],
       [0.3772946 , 0.77321814, 0.70363354]])

In [57]:
np.set_printoptions(precision=3)

In [58]:
arr

array([[0.689, 0.356, 0.48 ],
       [0.315, 0.487, 0.004],
       [0.012, 0.8  , 0.493],
       [0.083, 0.689, 0.546],
       [0.377, 0.773, 0.704]])

In [59]:
arr=np.random.random((5,3))
arr

array([[0.025, 0.55 , 0.211],
       [0.076, 0.161, 0.44 ],
       [0.356, 0.549, 0.156],
       [0.854, 0.096, 0.558],
       [0.534, 0.042, 0.7  ]])

In [60]:
np.set_printoptions(precision=6)

In [61]:
arr

array([[0.024556, 0.550102, 0.211482],
       [0.075749, 0.161237, 0.439877],
       [0.355878, 0.548591, 0.155811],
       [0.85432 , 0.096207, 0.557907],
       [0.534127, 0.041508, 0.699983]])

In [62]:
#np.set_printoptions(precision=4)# by this function we can change the no of place of float to be displayed in numpy

In [63]:
a=["pen","pencil","axoim","cell phone","abc","def"]
b=[]
c=a[:]
for item in c:
    items=a.pop()
    b.append(items)
print(a) 
print(b)


[]
['def', 'abc', 'cell phone', 'axoim', 'pencil', 'pen']


In [64]:
a

[]

In [65]:
# Q 22
a=np.arange(15)

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
np.set_printoptions(threshold=6)

In [68]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [69]:
#np.set_printoptions(threshold=6)
# by this we can limit the no of max element of array to be print

In [70]:
np.set_printoptions(threshold=np.inf)

In [71]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
# Q 23

In [74]:
names=np.array(['bushra','iqra','faiza','bushra'])

In [79]:
cd=names=='bushra'

In [76]:
arr=np.arange(12).reshape(4,3)

In [77]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
arr[cd]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [83]:
arr[names=='bushra',2]

array([ 2, 11])